### PR TITLE
AIRO-1625 Add capsule shape

### PR DESCRIPTION
**Pull request by woven-suomi-tanishige**
## Proposed change(s)

Added capsule shape support

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

[issue](https://github.com/Unity-Technologies/URDF-Importer/issues/162)

### Types of change(s)

- [ ] Bug fix
- [x] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe)

## Testing and Verification
Please describe the tests that you ran to verify your changes. Please also provide instructions, ROS packages, and Unity project files as appropriate so we can reproduce the test environment.

### Test Configuration:
- Unity Version: [e.g. Unity 2020.2.0f1]
- Unity machine OS + version: [e.g. Windows 10]
- ROS machine OS + version: [e.g. Ubuntu 18.04, ROS Noetic]
- ROS–Unity communication: [e.g. Docker]

## Checklist
- [x] Ensured this PR is up-to-date with the `dev` branch
- [x] Created this PR to target the `dev` branch
- [x] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/URDF-Importer/blob/main/CONTRIBUTING.md)
- [x] Added tests that prove my fix is effective or that my feature works
- [ ] Increased the [test coverage criteria](https://github.com/Unity-Technologies/URDF-Importer/blob/dev/.yamato/yamato-config.yml#L18) by 3%
- [x] Updated the [Changelog](https://github.com/Unity-Technologies/URDF-Importer/blob/dev/com.unity.robotics.urdf-importer/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/URDF-Importer/blob/dev/com.unity.robotics.urdf-importer/CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate

## Other comments

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/URDF-Importer?pullRequest=163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/URDF-Importer?pullRequest=163) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/URDF-Importer?pullRequest=163) it.</sub>

**Review by at669 — APPROVED** [review]
Tested and looks good to me! Approving pending @vidurvij-Unity's review, and review of the CLA from @woven-suomi-tanishige.

**Comment by woven-suomi-tanishige** [comment]
Hi, @vidurvij-Unity
Could you please move forward with this review?

**Comment by vidurvij-Unity** [comment]
I reviewed, everything sees great. Could give me the write rights as I need to merge dev branch form this repo to the branch being merged.

**Comment by vidurvij-Unity** [comment]
Never mind. I have changed the base to an intermediary branch on which our internal tests can be run.

**Pull request merged**
