### PR TITLE
AIRO-1504 Fix IsRevoluteOrContinuous in UrdfJoint.cs

### PR DESCRIPTION
**Pull request by rmanky**
## Proposed change(s)

This PR updated UrdfJoint.cs to correct an issue with the `IsRevoluteOrContinuous` var that previously only checked if the joint was a `Revolute`

### Useful links (GitHub issues, JIRA tickets, forum threads, etc.)

None

### Types of change(s)

- [x] Bug fix
- [ ] New feature
- [ ] Code refactor
- [ ] Documentation update
- [ ] Other (please describe)

## Testing and Verification

Please describe the tests that you ran to verify your changes. Please also provide instructions, ROS packages, and Unity project files as appropriate so we can reproduce the test environment. 

### Test Configuration:
- Unity Version: Unity 2021.2.1
- Unity machine OS + version: Arch Linux
- ROS machine OS + version: Ubuntu 18.04
- ROS–Unity communication: Docker

## Checklist
- [x] Ensured this PR is up-to-date with the `dev` branch
- [x] Created this PR to target the `dev` branch
- [x] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/URDF-Importer/blob/main/CONTRIBUTING.md)
- [ ] Added tests that prove my fix is effective or that my feature works
- [ ] Increased the [test coverage criteria](https://github.com/Unity-Technologies/URDF-Importer/blob/dev/.yamato/yamato-config.yml#L18) by 3%
- [ ] Updated the [Changelog](https://github.com/Unity-Technologies/URDF-Importer/blob/dev/com.unity.robotics.urdf-importer/CHANGELOG.md) and described changes in the [Unreleased section](https://github.com/Unity-Technologies/URDF-Importer/blob/dev/com.unity.robotics.urdf-importer/CHANGELOG.md#unreleased)
- [ ] Updated the documentation as appropriate

## Other comments

Seems like a simple fix, the previous version didn't really make sense? To be fair I'm not quite sure what this file is for, I'm just using it to publish joint data back to ROS in my own script (I needed the joint name, which was stored on each Articulation Body in this component).

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/URDF-Importer?pullRequest=158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/URDF-Importer?pullRequest=158) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/URDF-Importer?pullRequest=158) it.</sub>

**Review by peifeng-unity — APPROVED** [review]
Thank you, @rmanky!

**Comment by peifeng-unity** [comment]
The Yamato check cannot be triggered from a forked repository. I'll try to merge this branch to one of the local branches before merging to dev.

**Comment by peifeng-unity** [comment]
Will create another PR from the `external-intermediate` branch to `dev`.

**Pull request merged**
