### PR TITLE
Feature/collision primitive support

### PR DESCRIPTION
**Pull request by micahpearlman**
This is not really tested but perhaps it can help with issue: Issue Exporting Box Collider #79

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/URDF-Importer?pullRequest=83) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/URDF-Importer?pullRequest=83) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/URDF-Importer?pullRequest=83) it.</sub>

**Comment by mrpropellers** [comment]
Hi @micahpearlman, thanks for submitting this fix! A few process things need to be cleared up before we can accept this:

1. We're no longer accepting PR's for untested code. In order for this to be accepted, you would need to include some minimal tests [in the appropriate test directory](https://github.com/Unity-Technologies/URDF-Importer/tree/main/com.unity.robotics.urdf-importer/Tests) to confirm your additions are working as intended.
2. This PR is made against `main`, but only `dev` is allowed to be merged into `main`. All new feature work and bugfixes must be submitted against `dev`. 
3. In order for us to accept any of your contributions, you must first sign the Contributor License Agreement linked above by the unity-cla-assistant.

Please see our [Contribution Guidelines](https://github.com/Unity-Technologies/URDF-Importer/blob/main/CONTRIBUTING.md) for a more complete view of our current expectations. This is a bug that I'm planning on resolving this week, so I'm happy to spend some time reviewing any changes you make, or if you prefer I can take over this branch and re-submit it with required updates. Totally up to you, though! Let me know if you have any questions.

**Comment by micahpearlman** [comment]
@mrpropellers you can go ahead and reject the pull request. Was sent over as a potential starting point to implement the feature request for #79 and not necessarily as a fully tested production ready feature. Also, the CLA seems a little odd?  I’ve never seen anything like that for an OSS project?  Hard, at least for me, to understand the legalize without getting a professional involved.

**Comment by mrpropellers** [comment]
@micahpearlman I tend to agree, and you may be able to track down some PRs where I voiced similar objections to its addition, but it's unfortunately required per company policy! If you know of other Unity OSS projects that don't have one of these in place, please don't tell me about them 😄

**Comment by micahpearlman** [comment]
That’s a shame. I would have likely been a regular contributor and user of this project. Having to retain a IP lawyer or fear potential legal action from a large company feels a little bit against the OSS ethos.

**Comment by mrpropellers** [comment]
Understood. Will be happy to relay that feedback internally when we next discuss our OSS curation!

**Pull request closed without merging**
