### PR TITLE
Laurie/rigidbody editor

### PR DESCRIPTION
**Pull request by LaurieCheers-unity**

### CODE REVIEW

**Comment by peifeng-unity** [comment]
LGTM

Can we keep the center of mass and inertias visible in the editor at runtime as well. For example,

```
Rigidbody _rigidbody = (Rigidbody)target;
if (!EditorApplication.isPlaying)
{
    _rigidbody.centerOfMass = EditorGUILayout.Vector3Field("Center Of Mass", _rigidbody.centerOfMass);
    _rigidbody.inertiaTensor = EditorGUILayout.Vector3Field("Inertia Tensor", _rigidbody.inertiaTensor);

    Vector3 inertiaTensorEuler = _rigidbody.inertiaTensorRotation.eulerAngles;
    Vector3 newEuler = EditorGUILayout.Vector3Field("Inertia Tensor Rotation", inertiaTensorEuler);
    if (inertiaTensorEuler != newEuler)
    {
        _rigidbody.inertiaTensorRotation = Quaternion.Euler(newEuler);
    }
}
else 
{
    EditorGUILayout.Vector3Field("Center Of Mass", _rigidbody.centerOfMass);
    EditorGUILayout.Vector3Field("Inertia Tensor", _rigidbody.inertiaTensor);
    EditorGUILayout.Vector3Field("Inertia Tensor Rotation", _rigidbody.inertiaTensorRotation.eulerAngles);
}
```

**Review by peifeng-unity — COMMENTED** [review]
LGTM

Can we keep the center of mass and inertias visible in the inspector at runtime as well. For example,

```
Rigidbody _rigidbody = (Rigidbody)target;
if (!EditorApplication.isPlaying)
{
    _rigidbody.centerOfMass = EditorGUILayout.Vector3Field("Center Of Mass", _rigidbody.centerOfMass);
    _rigidbody.inertiaTensor = EditorGUILayout.Vector3Field("Inertia Tensor", _rigidbody.inertiaTensor);

    Vector3 inertiaTensorEuler = _rigidbody.inertiaTensorRotation.eulerAngles;
    Vector3 newEuler = EditorGUILayout.Vector3Field("Inertia Tensor Rotation", inertiaTensorEuler);
    if (inertiaTensorEuler != newEuler)
    {
        _rigidbody.inertiaTensorRotation = Quaternion.Euler(newEuler);
    }
}
else 
{
    EditorGUILayout.Vector3Field("Center Of Mass", _rigidbody.centerOfMass);
    EditorGUILayout.Vector3Field("Inertia Tensor", _rigidbody.inertiaTensor);
    EditorGUILayout.Vector3Field("Inertia Tensor Rotation", _rigidbody.inertiaTensorRotation.eulerAngles);
}
```

**Comment by peifeng-unity** [comment]
In addition, a minor thing of [Unity coding standard](https://ono.unity3d.com/unity-extra/unity-meta/raw/@/ReferenceSource/CSharp/Assets/CSharpReference.cs). We may change `_rigidbody` to `m_rigidbody`?

```
- Use prefix + PascalCase for non-public field naming.
        - Prefixes: m_ = instance field, s_ = static readwrite field, k_ = const
```

**Comment by LaurieCheers-unity** [comment]
> In addition, a minor thing of [Unity coding standard](https://ono.unity3d.com/unity-extra/unity-meta/raw/@/ReferenceSource/CSharp/Assets/CSharpReference.cs). We may change `_rigidbody` to `m_rigidbody`?
> 
> ```
> - Use prefix + PascalCase for non-public field naming.
>         - Prefixes: m_ = instance field, s_ = static readwrite field, k_ = const
> ```

It's a local variable, not a field, so should be lowercase with no prefix.

**Review by peifeng-unity — APPROVED** [review]

**Pull request merged**
